// Role-based permissions
export const ROLE_PERMISSIONS = {
    // Full access roles
    'Admin': {
        canManageMembers: true,
        canManageServices: true,
        canManageAnnouncements: true,
        canViewStore: true,
        canManageOrders: true,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'IT Admin': {
        canManageMembers: true,
        canManageServices: true,
        canManageAnnouncements: true,
        canViewStore: true,
        canManageOrders: false,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'Acct Admin': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: true,
        canTakeAttendance: false,
        canViewReports: true,
    },
    'Golf Charlie': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: true,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'Alpha Golf Charlie': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: true,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'Golf Serial': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: true,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'Alpha Golf Serial': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: true,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'Senior Commander I': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: false,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'Senior Commander II': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: false,
        canTakeAttendance: true,
        canViewReports: true,
    },
    'Secretary': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: true,
        canTakeAttendance: true,
        canViewReports: false,
    },
    'Member': {
        canManageMembers: false,
        canManageServices: false,
        canManageAnnouncements: false,
        canViewStore: true,
        canManageOrders: false,
        canTakeAttendance: false,
        canViewReports: false,
    },
};

export const getRoleTabs = (role) => {
    const baseTabs = ['Home', 'Store', 'Cart', 'Orders', 'Attendance'];
    const roleTabs = {
        'Admin': [...baseTabs, 'IT Admin', 'Attendance Report', 'Profile'],
        'IT Admin': [...baseTabs, 'IT Admin', 'Attendance Report', 'Profile'],
        'Acct Admin': [...baseTabs, 'Acct Admin', 'Profile'],
        'Golf Charlie': [...baseTabs, 'Profile', 'Attendance Report'],
        'Alpha Golf Charlie': [...baseTabs, 'Profile'],
        'Golf Serial': [...baseTabs, 'IT Admin', 'Acct Admin', 'Profile', 'Attendance Report'],
        'Alpha Golf Serial': [...baseTabs, 'Profile', 'Attendance Report'],
        'Senior Commander I': [...baseTabs, 'Profile'],
        'Senior Commander II': [...baseTabs, 'Profile'],
        'Secretary': [...baseTabs, 'Profile'],
        'Member': [...baseTabs, 'Profile'],
    };
    return roleTabs[role] || baseTabs;
};